package tp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.io.StringWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.web.client.RestTemplate;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

/**
 *
 * @author said
 */
public class ClientApp extends javax.swing.JFrame {

    /**
     * Creates new form ClientApp
     */
    public ClientApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        resumeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        affichage = new javax.swing.JTextArea();
        statsBtn = new javax.swing.JButton();
        detailsBtn = new javax.swing.JButton();
        rechercheTxt = new javax.swing.JTextField();
        rechercheBtn = new javax.swing.JButton();
        depotBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PmtId = new javax.swing.JTextField();
        InstdAmt = new javax.swing.JTextField();
        DtOfSgntr = new javax.swing.JTextField();
        BIC = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        MndtId = new javax.swing.JTextField();
        IBAN = new javax.swing.JTextField();
        RmtInf = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        resumeBtn.setText("resume");
        resumeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeBtnActionPerformed(evt);
            }
        });

        affichage.setEditable(false);
        affichage.setColumns(20);
        affichage.setRows(5);
        jScrollPane1.setViewportView(affichage);

        statsBtn.setText("stats");
        statsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsBtnActionPerformed(evt);
            }
        });

        detailsBtn.setText("details");
        detailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBtnActionPerformed(evt);
            }
        });

        rechercheTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheTxtActionPerformed(evt);
            }
        });

        rechercheBtn.setText("recherche");
        rechercheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheBtnActionPerformed(evt);
            }
        });

        depotBtn.setText("deposer un ficher");
        depotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depotBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("PmtId :");

        jLabel2.setText("InstdAmt :");

        jLabel3.setText("MndtId :");

        jLabel4.setText("DtOfSgntr :");

        jLabel5.setText("BIC :");

        jLabel6.setText("Name :");

        jLabel7.setText("IBAN :");

        jLabel8.setText("RmtInf :");

        sendBtn.setText("Envoi");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rechercheTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercheBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depotBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RmtInf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BIC, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DtOfSgntr, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InstdAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PmtId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MndtId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendBtn)
                                .addGap(47, 47, 47)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resumeBtn)
                    .addComponent(statsBtn)
                    .addComponent(detailsBtn)
                    .addComponent(rechercheTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercheBtn)
                    .addComponent(depotBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PmtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InstdAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MndtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DtOfSgntr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(RmtInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(sendBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void resumeBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	RestTemplate restTemplate = new RestTemplate();
        String resultText = restTemplate.getForObject("http://localhost:8080/rest-service/resume", String.class);
        affichage.setText(parseXml(resultText));        
    }                                         

    private void statsBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	RestTemplate restTemplate2 = new RestTemplate();
        String resultText2 = restTemplate2.getForObject("http://localhost:8080/rest-service/stats", String.class);
        affichage.setText(parseXml(resultText2));        
    }                                        

    private void detailsBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	RestTemplate restTemplate = new RestTemplate();
        String resultText = restTemplate.getForObject("http://localhost:8080/rest-service/detail", String.class);
        affichage.setText(parseXml(resultText));        
    }                                          

    private void depotBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	JFileChooser chooser = new JFileChooser();
        chooser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (chooser.getSelectedFile() != null) {
                    if (!(chooser.getSelectedFile().getName().endsWith(".xml"))) {
                        JOptionPane.showMessageDialog(new JFrame(),"veuillez choisir un format xml", "Erreur Format Fichier",
                                JOptionPane.ERROR_MESSAGE);                              
                    } else {
                                                          
                              RestTemplate template = new RestTemplate();
                              Path path = Paths.get(chooser.getSelectedFile().getPath());
                              String str = "";
                          	try {
                          		List<String> strlist = Files.readAllLines(path);
                          		for (int i = 0; i < strlist.size(); i++) {
                      				str += strlist.get(i);
                      			}
                          		Document doc = postRequest("http://localhost:8080/rest-service/depot/", str);
                        		JOptionPane.showMessageDialog(null, "transaction enregistrer !");
                                         			
                      		} catch (Exception ex) {
                      			JOptionPane.showMessageDialog(null, "transation existe deja !");
                      		}
                              
                    }    
                }
            }
        });
        chooser.showOpenDialog(null);
    }                                        

    private void rechercheBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	try {
			String str = rechercheTxt.getText();
			RestTemplate restTemplate = new RestTemplate();
			String resultText = restTemplate.getForObject("http://localhost:8080/rest-service/trx/"+str, String.class);
			affichage.setText(parseXml(resultText));
		} catch (Exception e) {
			rechercheTxt.setText("");
			JOptionPane.showMessageDialog(null, "PmtId non existant !");
		}
    }                                            

    private void rechercheTxtActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	rechercheBtn.doClick();
    }                                            

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	String str = new String("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
				+"<DrctDbtTxInf>"+
				"<PmtId>"+PmtId.getText()+"</PmtId>"+
				"<InstdAmt>"+InstdAmt.getText()+"</InstdAmt>"+
				"<DrctDbtTx>"+
					"<MndtRltdInf>"+
						"<MndtId>"+MndtId.getText()+"</MndtId>"+
						"<DtOfSgntr>"+DtOfSgntr.getText()+"</DtOfSgntr>"+
					"</MndtRltdInf>"+
				"</DrctDbtTx>"+
				"<DbtrAgt>"+
					"<FinInstnId>"+
						"<BIC>"+BIC.getText()+"</BIC>"+
					"</FinInstnId>"+
				"</DbtrAgt>"+
				"<Dbtr>"+
					"<Nm>"+Name.getText()+"</Nm>"+
				"</Dbtr>"+
				"<DbtrAcct>"+
					"<Id>"+
						"<IBAN>"+IBAN.getText()+"</IBAN>"+
					"</Id>"+
				"</DbtrAcct>"+
				"<RmtInf>"+RmtInf.getText()+"</RmtInf>"+
			"</DrctDbtTxInf>");
    	
    	RestTemplate template = new RestTemplate();
        try {
    		Document doc = postRequest("http://localhost:8080/rest-service/depot/", str);
    		JOptionPane.showMessageDialog(null, "transaction enregistrer !");
                     			
  		} catch (Exception ex) {
  			JOptionPane.showMessageDialog(null, "transation existe deja !");
  		}
        RmtInf.setText(""); IBAN.setText(""); Name.setText(""); BIC.setText("");
        PmtId.setText(""); InstdAmt.setText(""); MndtId.setText(""); DtOfSgntr.setText("");
        
    }
    
    private String parseXml(String text){
        RestTemplate restTemplate = new RestTemplate();
                restTemplate.getMessageConverters()
                .add(0, new StringHttpMessageConverter(Charset.forName("UTF-8")));
                  
                StringWriter stringWriter = new StringWriter();
                StreamResult xmlOutput = new StreamResult(stringWriter);
                TransformerFactory tf = TransformerFactory.newInstance();
                
                
                Transformer transformer;
                try {
                    transformer = tf.newTransformer();
                    transformer.setOutputProperty(OutputKeys.METHOD, "xml");
                    transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "8");
                    transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");
                    transformer.setOutputProperty(OutputKeys.INDENT, "yes");
                    transformer.transform(new StreamSource(new StringReader(text)), xmlOutput);

                
                } catch (TransformerConfigurationException ex) {
                    Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TransformerException ex) {
            Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
        }
                return xmlOutput.getWriter().toString();
    }
    
    public Document postRequest(String url, String xml) throws SAXException, ParserConfigurationException{
		try{
	        URL obj = new URL(url);
	        HttpURLConnection con = (HttpURLConnection) obj.openConnection();
	        con.setRequestMethod("POST");
	        con.setRequestProperty("Content-Type",
	                "application/xml;charset=utf-8");
	        String urlParameters = xml;
	        con.setDoOutput(true);
	        DataOutputStream wr = new DataOutputStream(con.getOutputStream());
	        wr.writeBytes(urlParameters);
	        wr.flush();
	        wr.close();
	        String responseStatus = con.getResponseMessage();
	
	        BufferedReader in = new BufferedReader(new InputStreamReader(
	                con.getInputStream()));
	        String inputLine;
	        StringBuffer response = new StringBuffer();
	        while ((inputLine = in.readLine()) != null) {
	            response.append(inputLine);
	        }
	        in.close();
	        return (Document) DocumentBuilderFactory.newInstance().newDocumentBuilder()
		            .parse(new InputSource(new StringReader(response.toString())));
		}catch(IOException e){
			return null;
		}
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField BIC;
    private javax.swing.JTextField DtOfSgntr;
    private javax.swing.JTextField IBAN;
    private javax.swing.JTextField InstdAmt;
    private javax.swing.JTextField MndtId;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PmtId;
    private javax.swing.JTextField RmtInf;
    private javax.swing.JTextArea affichage;
    private javax.swing.JButton depotBtn;
    private javax.swing.JButton detailsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rechercheBtn;
    private javax.swing.JTextField rechercheTxt;
    private javax.swing.JButton resumeBtn;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton statsBtn;
    // End of variables declaration                   
}
